/*
SQLyog Ultimate v13.1.1 (64 bit)
MySQL - 10.3.18-MariaDB-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('1','AD','Andorra','Andorra la Vella','EUR','376','^(?:AD)*(d{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('2','AE','United Arab Emirates','Abu Dhabi','AED','971','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('3','AF','Afghanistan','Kabul','AFN','93','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('4','AG','Antigua and Barbuda','St. John\'s','XCD','+1-268','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('5','AI','Anguilla','The Valley','XCD','+1-264','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('6','AL','Albania','Tirana','ALL','355','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('7','AM','Armenia','Yerevan','AMD','374','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('8','AN','Netherlands Antilles','Willemstad','ANG','599','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('9','AO','Angola','Luanda','AOA','244','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('10','AQ','Antarctica','','','','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('11','AR','Argentina','Buenos Aires','ARS','54','^([A-Z]d{4}[A-Z]{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('12','AS','American Samoa','Pago Pago','USD','+1-684','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('13','AT','Austria','Vienna','EUR','43','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('14','AU','Australia','Canberra','AUD','61','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('15','AW','Aruba','Oranjestad','AWG','297','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('16','AX','Aland Islands','Mariehamn','EUR','+358-18','^(?:FI)*(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('17','AZ','Azerbaijan','Baku','AZN','994','^(?:AZ)*(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('18','BA','Bosnia and Herzegovina','Sarajevo','BAM','387','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('19','BB','Barbados','Bridgetown','BBD','+1-246','^(?:BB)*(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('20','BD','Bangladesh','Dhaka','BDT','880','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('21','BE','Belgium','Brussels','EUR','32','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('22','BF','Burkina Faso','Ouagadougou','XOF','226','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('23','BG','Bulgaria','Sofia','BGN','359','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('24','BH','Bahrain','Manama','BHD','973','^(d{3}d?)$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('25','BI','Burundi','Bujumbura','BIF','257','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('26','BJ','Benin','Porto-Novo','XOF','+229','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('27','BL','Saint Barthelemy','Gustavia','EUR','590','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('28','BM','Bermuda','Hamilton','BMD','+1-441','^([A-Z]{2}d{2})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('29','BN','Brunei','Bandar Seri Begawan','BND','673','^([A-Z]{2}d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('30','BO','Bolivia','Sucre','BOB','591','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('31','BQ','Bonaire, Saint Eustatius and Saba ','','USD','599','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('32','BR','Brazil','Brasilia','BRL','55','^(d{8})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('33','BS','Bahamas','Nassau','BSD','+1-242','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('34','BT','Bhutan','Thimphu','BTN','975','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('35','BV','Bouvet Island','','NOK','','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('36','BW','Botswana','Gaborone','BWP','267','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('37','BY','Belarus','Minsk','BYR','375','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('38','BZ','Belize','Belmopan','BZD','501','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('39','CA','Canada','Ottawa','CAD','1','^([ABCEGHJKLMNPRSTVXY]d[ABCEGHJKLMNPRSTVWXYZ]) ?(d[ABCEGHJKLMNPRSTVWXYZ]d)$ ');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('40','CC','Cocos Islands','West Island','AUD','61','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('41','CD','Democratic Republic of the Congo','Kinshasa','CDF','243','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('42','CF','Central African Republic','Bangui','XAF','236','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('43','CG','Republic of the Congo','Brazzaville','XAF','242','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('44','CH','Switzerland','Berne','CHF','41','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('45','CI','Ivory Coast','Yamoussoukro','XOF','225','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('46','CK','Cook Islands','Avarua','NZD','682','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('47','CL','Chile','Santiago','CLP','56','^(d{7})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('48','CM','Cameroon','Yaounde','XAF','237','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('49','CN','China','Beijing','CNY','86','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('50','CO','Colombia','Bogota','COP','57','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('51','CR','Costa Rica','San Jose','CRC','506','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('52','CS','Serbia and Montenegro','Belgrade','RSD','381','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('53','CU','Cuba','Havana','CUP','53','^(?:CP)*(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('54','CV','Cape Verde','Praia','CVE','238','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('55','CW','Curacao',' Willemstad','ANG','599','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('56','CX','Christmas Island','Flying Fish Cove','AUD','61','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('57','CY','Cyprus','Nicosia','EUR','357','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('58','CZ','Czech Republic','Prague','CZK','420','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('59','DE','Germany','Berlin','EUR','49','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('60','DJ','Djibouti','Djibouti','DJF','253','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('61','DK','Denmark','Copenhagen','DKK','45','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('62','DM','Dominica','Roseau','XCD','+1-767','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('63','DO','Dominican Republic','Santo Domingo','DOP','+809/829/849','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('64','DZ','Algeria','Algiers','DZD','213','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('65','EC','Ecuador','Quito','USD','593','^([a-zA-Z]d{4}[a-zA-Z])$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('66','EE','Estonia','Tallinn','EUR','372','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('67','EG','Egypt','Cairo','EGP','20','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('68','EH','Western Sahara','El-Aaiun','MAD','212','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('69','ER','Eritrea','Asmara','ERN','291','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('70','ES','Spain','Madrid','EUR','34','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('71','ET','Ethiopia','Addis Ababa','ETB','251','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('72','FI','Finland','Helsinki','EUR','358','^(?:FI)*(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('73','FJ','Fiji','Suva','FJD','679','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('74','FK','Falkland Islands','Stanley','FKP','500','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('75','FM','Micronesia','Palikir','USD','691','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('76','FO','Faroe Islands','Torshavn','DKK','298','^(?:FO)*(d{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('77','FR','France','Paris','EUR','33','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('78','GA','Gabon','Libreville','XAF','241','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('79','GD','Grenada','St. George\'s','XCD','+1-473','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('80','GE','Georgia','Tbilisi','GEL','995','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('81','GF','French Guiana','Cayenne','EUR','594','^((97|98)3d{2})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('82','GG','Guernsey','St Peter Port','GBP','+44-1481','^(([A-Z]d{2}[A-Z]{2})|([A-Z]d{3}[A-Z]{2})|([A-Z]{2}d{2}[A-Z]{2})|([A-Z]{2}d{3}[A-Z]{2})|([A-Z]d[A-Z]d[A-Z]{2})|([A-Z]{2}d[A-Z]d[A-Z]{2})|(GIR0AA))$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('83','GH','Ghana','Accra','GHS','233','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('84','GI','Gibraltar','Gibraltar','GIP','350','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('85','GL','Greenland','Nuuk','DKK','299','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('86','GM','Gambia','Banjul','GMD','220','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('87','GN','Guinea','Conakry','GNF','224','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('88','GP','Guadeloupe','Basse-Terre','EUR','590','^((97|98)d{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('89','GQ','Equatorial Guinea','Malabo','XAF','240','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('90','GR','Greece','Athens','EUR','30','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('91','GS','South Georgia and the South Sandwich Islands','Grytviken','GBP','','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('92','GT','Guatemala','Guatemala City','GTQ','502','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('93','GU','Guam','Hagatna','USD','+1-671','^(969d{2})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('94','GW','Guinea-Bissau','Bissau','XOF','245','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('95','GY','Guyana','Georgetown','GYD','592','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('96','HK','Hong Kong','Hong Kong','HKD','852','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('97','HM','Heard Island and McDonald Islands','','AUD',' ','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('98','HN','Honduras','Tegucigalpa','HNL','504','^([A-Z]{2}d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('99','HR','Croatia','Zagreb','HRK','385','^(?:HR)*(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('100','HT','Haiti','Port-au-Prince','HTG','509','^(?:HT)*(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('101','HU','Hungary','Budapest','HUF','36','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('102','ID','Indonesia','Jakarta','IDR','62','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('103','IE','Ireland','Dublin','EUR','353','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('104','IL','Israel','Jerusalem','ILS','972','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('105','IM','Isle of Man','Douglas, Isle of Man','GBP','+44-1624','^(([A-Z]d{2}[A-Z]{2})|([A-Z]d{3}[A-Z]{2})|([A-Z]{2}d{2}[A-Z]{2})|([A-Z]{2}d{3}[A-Z]{2})|([A-Z]d[A-Z]d[A-Z]{2})|([A-Z]{2}d[A-Z]d[A-Z]{2})|(GIR0AA))$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('106','IN','India','New Delhi','INR','91','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('107','IO','British Indian Ocean Territory','Diego Garcia','USD','246','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('108','IQ','Iraq','Baghdad','IQD','964','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('109','IR','Iran','Tehran','IRR','98','^(d{10})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('110','IS','Iceland','Reykjavik','ISK','354','^(d{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('111','IT','Italy','Rome','EUR','39','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('112','JE','Jersey','Saint Helier','GBP','+44-1534','^(([A-Z]d{2}[A-Z]{2})|([A-Z]d{3}[A-Z]{2})|([A-Z]{2}d{2}[A-Z]{2})|([A-Z]{2}d{3}[A-Z]{2})|([A-Z]d[A-Z]d[A-Z]{2})|([A-Z]{2}d[A-Z]d[A-Z]{2})|(GIR0AA))$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('113','JM','Jamaica','Kingston','JMD','+1-876','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('114','JO','Jordan','Amman','JOD','962','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('115','JP','Japan','Tokyo','JPY','81','^(d{7})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('116','KE','Kenya','Nairobi','KES','254','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('117','KG','Kyrgyzstan','Bishkek','KGS','996','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('118','KH','Cambodia','Phnom Penh','KHR','855','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('119','KI','Kiribati','Tarawa','AUD','686','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('120','KM','Comoros','Moroni','KMF','269','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('121','KN','Saint Kitts and Nevis','Basseterre','XCD','+1-869','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('122','KP','North Korea','Pyongyang','KPW','850','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('123','KR','South Korea','Seoul','KRW','82','^(?:SEOUL)*(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('124','KW','Kuwait','Kuwait City','KWD','965','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('125','KY','Cayman Islands','George Town','KYD','+1-345','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('126','KZ','Kazakhstan','Astana','KZT','7','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('127','LA','Laos','Vientiane','LAK','856','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('128','LB','Lebanon','Beirut','LBP','961','^(d{4}(d{4})?)$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('129','LC','Saint Lucia','Castries','XCD','+1-758','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('130','LI','Liechtenstein','Vaduz','CHF','423','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('131','LK','Sri Lanka','Colombo','LKR','94','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('132','LR','Liberia','Monrovia','LRD','231','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('133','LS','Lesotho','Maseru','LSL','266','^(d{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('134','LT','Lithuania','Vilnius','EUR','370','^(?:LT)*(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('135','LU','Luxembourg','Luxembourg','EUR','352','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('136','LV','Latvia','Riga','EUR','371','^(?:LV)*(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('137','LY','Libya','Tripolis','LYD','218','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('138','MA','Morocco','Rabat','MAD','212','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('139','MC','Monaco','Monaco','EUR','377','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('140','MD','Moldova','Chisinau','MDL','373','^(?:MD)*(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('141','ME','Montenegro','Podgorica','EUR','382','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('142','MF','Saint Martin','Marigot','EUR','590','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('143','MG','Madagascar','Antananarivo','MGA','261','^(d{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('144','MH','Marshall Islands','Majuro','USD','692','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('145','MK','Macedonia','Skopje','MKD','389','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('146','ML','Mali','Bamako','XOF','223','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('147','MM','Myanmar','Nay Pyi Taw','MMK','95','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('148','MN','Mongolia','Ulan Bator','MNT','976','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('149','MO','Macao','Macao','MOP','853','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('150','MP','Northern Mariana Islands','Saipan','USD','+1-670','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('151','MQ','Martinique','Fort-de-France','EUR','596','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('152','MR','Mauritania','Nouakchott','MRO','222','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('153','MS','Montserrat','Plymouth','XCD','+1-664','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('154','MT','Malta','Valletta','EUR','356','^([A-Z]{3}d{2}d?)$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('155','MU','Mauritius','Port Louis','MUR','230','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('156','MV','Maldives','Male','MVR','960','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('157','MW','Malawi','Lilongwe','MWK','265','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('158','MX','Mexico','Mexico City','MXN','52','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('159','MY','Malaysia','Kuala Lumpur','MYR','60','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('160','MZ','Mozambique','Maputo','MZN','258','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('161','NA','Namibia','Windhoek','NAD','264','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('162','NC','New Caledonia','Noumea','XPF','687','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('163','NE','Niger','Niamey','XOF','227','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('164','NF','Norfolk Island','Kingston','AUD','672','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('165','NG','Nigeria','Abuja','NGN','234','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('166','NI','Nicaragua','Managua','NIO','505','^(d{7})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('167','NL','Netherlands','Amsterdam','EUR','31','^(d{4}[A-Z]{2})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('168','NO','Norway','Oslo','NOK','47','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('169','NP','Nepal','Kathmandu','NPR','977','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('170','NR','Nauru','Yaren','AUD','674','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('171','NU','Niue','Alofi','NZD','683','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('172','NZ','New Zealand','Wellington','NZD','64','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('173','OM','Oman','Muscat','OMR','968','^(d{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('174','PA','Panama','Panama City','PAB','507','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('175','PE','Peru','Lima','PEN','51','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('176','PF','French Polynesia','Papeete','XPF','689','^((97|98)7d{2})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('177','PG','Papua New Guinea','Port Moresby','PGK','675','^(d{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('178','PH','Philippines','Manila','PHP','63','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('179','PK','Pakistan','Islamabad','PKR','92','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('180','PL','Poland','Warsaw','PLN','48','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('181','PM','Saint Pierre and Miquelon','Saint-Pierre','EUR','508','^(97500)$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('182','PN','Pitcairn','Adamstown','NZD','870','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('183','PR','Puerto Rico','San Juan','USD','+1-787/1-939','^(d{9})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('184','PS','Palestinian Territory','East Jerusalem','ILS','970','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('185','PT','Portugal','Lisbon','EUR','351','^(d{7})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('186','PW','Palau','Melekeok','USD','680','^(96940)$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('187','PY','Paraguay','Asuncion','PYG','595','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('188','QA','Qatar','Doha','QAR','974','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('189','RE','Reunion','Saint-Denis','EUR','262','^((97|98)(4|7|8)d{2})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('190','RO','Romania','Bucharest','RON','40','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('191','RS','Serbia','Belgrade','RSD','381','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('192','RU','Russia','Moscow','RUB','7','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('193','RW','Rwanda','Kigali','RWF','250','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('194','SA','Saudi Arabia','Riyadh','SAR','966','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('195','SB','Solomon Islands','Honiara','SBD','677','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('196','SC','Seychelles','Victoria','SCR','248','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('197','SD','Sudan','Khartoum','SDG','249','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('198','SE','Sweden','Stockholm','SEK','46','^(?:SE)*(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('199','SG','Singapore','Singapur','SGD','65','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('200','SH','Saint Helena','Jamestown','SHP','290','^(STHL1ZZ)$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('201','SI','Slovenia','Ljubljana','EUR','386','^(?:SI)*(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('202','SJ','Svalbard and Jan Mayen','Longyearbyen','NOK','47','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('203','SK','Slovakia','Bratislava','EUR','421','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('204','SL','Sierra Leone','Freetown','SLL','232','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('205','SM','San Marino','San Marino','EUR','378','^(4789d)$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('206','SN','Senegal','Dakar','XOF','221','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('207','SO','Somalia','Mogadishu','SOS','252','^([A-Z]{2}d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('208','SR','Suriname','Paramaribo','SRD','597','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('209','SS','South Sudan','Juba','SSP','211','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('210','ST','Sao Tome and Principe','Sao Tome','STD','239','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('211','SV','El Salvador','San Salvador','USD','503','^(?:CP)*(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('212','SX','Sint Maarten','Philipsburg','ANG','599','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('213','SY','Syria','Damascus','SYP','963','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('214','SZ','Swaziland','Mbabane','SZL','268','^([A-Z]d{3})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('215','TC','Turks and Caicos Islands','Cockburn Town','USD','+1-649','^(TKCA 1ZZ)$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('216','TD','Chad','N\'Djamena','XAF','235','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('217','TF','French Southern Territories','Port-aux-Francais','EUR','','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('218','TG','Togo','Lome','XOF','228','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('219','TH','Thailand','Bangkok','THB','66','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('220','TJ','Tajikistan','Dushanbe','TJS','992','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('221','TK','Tokelau','','NZD','690','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('222','TL','East Timor','Dili','USD','670','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('223','TM','Turkmenistan','Ashgabat','TMT','993','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('224','TN','Tunisia','Tunis','TND','216','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('225','TO','Tonga','Nuku\'alofa','TOP','676','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('226','TR','Turkey','Ankara','TRY','90','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('227','TT','Trinidad and Tobago','Port of Spain','TTD','+1-868','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('228','TV','Tuvalu','Funafuti','AUD','688','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('229','TW','Taiwan','Taipei','TWD','886','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('230','TZ','Tanzania','Dodoma','TZS','255','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('231','UA','Ukraine','Kiev','UAH','380','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('232','UG','Uganda','Kampala','UGX','256','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('233','UK','United Kingdom','London','GBP','44','^(([A-Z]d{2}[A-Z]{2})|([A-Z]d{3}[A-Z]{2})|([A-Z]{2}d{2}[A-Z]{2})|([A-Z]{2}d{3}[A-Z]{2})|([A-Z]d[A-Z]d[A-Z]{2})|([A-Z]{2}d[A-Z]d[A-Z]{2})|(GIR0AA))$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('234','UM','United States Minor Outlying Islands','','USD','1','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('235','US','United States','Washington','USD','1','^d{5}(-d{4})?$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('236','UY','Uruguay','Montevideo','UYU','598','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('237','UZ','Uzbekistan','Tashkent','UZS','998','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('238','VA','Vatican','Vatican City','EUR','379','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('239','VC','Saint Vincent and the Grenadines','Kingstown','XCD','+1-784','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('240','VE','Venezuela','Caracas','VEF','58','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('241','VG','British Virgin Islands','Road Town','USD','+1-284','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('242','VI','U.S. Virgin Islands','Charlotte Amalie','USD','+1-340','^d{5}(-d{4})?$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('243','VN','Vietnam','Hanoi','VND','84','^(d{6})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('244','VU','Vanuatu','Port Vila','VUV','678','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('245','WF','Wallis and Futuna','Mata Utu','XPF','681','^(986d{2})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('246','WS','Samoa','Apia','WST','685','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('247','XK','Kosovo','Pristina','EUR','','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('248','YE','Yemen','Sanaa','YER','967','');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('249','YT','Mayotte','Mamoudzou','EUR','262','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('250','ZA','South Africa','Pretoria','ZAR','27','^(d{4})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('251','ZM','Zambia','Lusaka','ZMW','260','^(d{5})$');
insert into `countries` (`id`, `code`, `name`, `capital`, `currency_code`, `phone`, `postal_code_regex`) values('252','ZW','Zimbabwe','Harare','ZWL','263','');
